package me.opims.dao;

import me.opims.entity.CommentDTO;
import me.opims.model.Firm;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface FirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    @Delete({
        "delete from firm",
        "where id_firm = #{idFirm,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idFirm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    @Insert({
        "insert into firm (id_firm, name_firm, ",
        "name_firmer, mail, ",
        "phone, zhanghao, ",
        "category)",
        "values (#{idFirm,jdbcType=INTEGER}, #{nameFirm,jdbcType=VARCHAR}, ",
        "#{nameFirmer,jdbcType=VARCHAR}, #{mail,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=INTEGER}, #{zhanghao,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=INTEGER})"
    })
    int insert(Firm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    int insertSelective(Firm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_firm, name_firm, name_firmer, mail, phone, zhanghao, category",
        "from firm",
        "where id_firm = #{idFirm,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Firm selectByPrimaryKey(Integer idFirm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Firm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbggenerated
     */
    @Update({
        "update firm",
        "set name_firm = #{nameFirm,jdbcType=VARCHAR},",
          "name_firmer = #{nameFirmer,jdbcType=VARCHAR},",
          "mail = #{mail,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=INTEGER},",
          "zhanghao = #{zhanghao,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=INTEGER}",
        "where id_firm = #{idFirm,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Firm record);

    List<Firm> selectFirmsByName(@Param("name") String name);

    CommentDTO selectCommentInfo(@Param("id") Integer id);
}