package me.opims.dao;

import me.opims.model.login;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface loginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    @Delete({
        "delete from login",
        "where zhanghao = #{zhanghao,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String zhanghao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    @Insert({
        "insert into login (zhanghao, password, ",
        "category)",
        "values (#{zhanghao,jdbcType=VARCHAR}, #{password,jdbcType=INTEGER}, ",
        "#{category,jdbcType=INTEGER})"
    })
    int insert(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    int insertSelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "zhanghao, password, category",
        "from login",
        "where zhanghao = #{zhanghao,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    login selectByPrimaryKey(String zhanghao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    @Update({
        "update login",
        "set password = #{password,jdbcType=INTEGER},",
          "category = #{category,jdbcType=INTEGER}",
        "where zhanghao = #{zhanghao,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(login record);
}