package me.opims.dao;

import me.opims.model.User;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user",
        "where id_user = #{idUser,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user (id_user, name_user, ",
        "name_real, mail, ",
        "phone, zhanghao, ",
        "category)",
        "values (#{idUser,jdbcType=INTEGER}, #{nameUser,jdbcType=VARCHAR}, ",
        "#{nameReal,jdbcType=VARCHAR}, #{mail,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=INTEGER}, #{zhanghao,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=INTEGER})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id_user, name_user, name_real, mail, phone, zhanghao, category",
        "from user",
        "where id_user = #{idUser,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    User selectByPrimaryKey(Integer idUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Update({
        "update user",
        "set name_user = #{nameUser,jdbcType=VARCHAR},",
          "name_real = #{nameReal,jdbcType=VARCHAR},",
          "mail = #{mail,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=INTEGER},",
          "zhanghao = #{zhanghao,jdbcType=VARCHAR},",
          "category = #{categor,jdbcType=INTEGER}",
        "where id_user = #{idUser,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);

    @Update({
            "update user",
            "set category = #{category}",
            "where id_user = #{idUser}"
    })
    int updateUserCategoryById(@Param("id_user") Integer id_user,@Param("category") int category);

    List<User> selectUsersByname(@Param("name") String name);
}