package me.opims.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id_admin
     *
     * @mbggenerated
     */
    private Integer idAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.name_admin
     *
     * @mbggenerated
     */
    private String nameAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.zhanghao
     *
     * @mbggenerated
     */
    private String zhanghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id_admin
     *
     * @return the value of admin.id_admin
     *
     * @mbggenerated
     */
    public Integer getIdAdmin() {
        return idAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id_admin
     *
     * @param idAdmin the value for admin.id_admin
     *
     * @mbggenerated
     */
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name_admin
     *
     * @return the value of admin.name_admin
     *
     * @mbggenerated
     */
    public String getNameAdmin() {
        return nameAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name_admin
     *
     * @param nameAdmin the value for admin.name_admin
     *
     * @mbggenerated
     */
    public void setNameAdmin(String nameAdmin) {
        this.nameAdmin = nameAdmin == null ? null : nameAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbggenerated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbggenerated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.zhanghao
     *
     * @return the value of admin.zhanghao
     *
     * @mbggenerated
     */
    public String getZhanghao() {
        return zhanghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.zhanghao
     *
     * @param zhanghao the value for admin.zhanghao
     *
     * @mbggenerated
     */
    public void setZhanghao(String zhanghao) {
        this.zhanghao = zhanghao == null ? null : zhanghao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.category
     *
     * @return the value of admin.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.category
     *
     * @param category the value for admin.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "idAdmin=" + idAdmin +
                ", nameAdmin='" + nameAdmin + '\'' +
                ", phone=" + phone +
                ", zhanghao='" + zhanghao + '\'' +
                ", category=" + category +
                '}';
    }
}