package me.opims.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id_comment
     *
     * @mbggenerated
     */
    private Integer idComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id_job
     *
     * @mbggenerated
     */
    private Integer idJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id_user
     *
     * @mbggenerated
     */
    private Integer idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_delete
     *
     * @mbggenerated
     */
    private Byte isDelete;


    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id_comment
     *
     * @return the value of comment.id_comment
     *
     * @mbggenerated
     */
    public Integer getIdComment() {
        return idComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id_comment
     *
     * @param idComment the value for comment.id_comment
     *
     * @mbggenerated
     */
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id_job
     *
     * @return the value of comment.id_job
     *
     * @mbggenerated
     */
    public Integer getIdJob() {
        return idJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id_job
     *
     * @param idJob the value for comment.id_job
     *
     * @mbggenerated
     */
    public void setIdJob(Integer idJob) {
        this.idJob = idJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id_user
     *
     * @return the value of comment.id_user
     *
     * @mbggenerated
     */
    public Integer getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id_user
     *
     * @param idUser the value for comment.id_user
     *
     * @mbggenerated
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_delete
     *
     * @return the value of comment.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_delete
     *
     * @param isDelete the value for comment.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}