package me.opims.model;

public class Firm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.id_firm
     *
     * @mbggenerated
     */
    private Integer idFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.name_firm
     *
     * @mbggenerated
     */
    private String nameFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.name_firmer
     *
     * @mbggenerated
     */
    private String nameFirmer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.zhanghao
     *
     * @mbggenerated
     */
    private String zhanghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.id_firm
     *
     * @return the value of firm.id_firm
     *
     * @mbggenerated
     */
    public Integer getIdFirm() {
        return idFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.id_firm
     *
     * @param idFirm the value for firm.id_firm
     *
     * @mbggenerated
     */
    public void setIdFirm(Integer idFirm) {
        this.idFirm = idFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.name_firm
     *
     * @return the value of firm.name_firm
     *
     * @mbggenerated
     */
    public String getNameFirm() {
        return nameFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.name_firm
     *
     * @param nameFirm the value for firm.name_firm
     *
     * @mbggenerated
     */
    public void setNameFirm(String nameFirm) {
        this.nameFirm = nameFirm == null ? null : nameFirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.name_firmer
     *
     * @return the value of firm.name_firmer
     *
     * @mbggenerated
     */
    public String getNameFirmer() {
        return nameFirmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.name_firmer
     *
     * @param nameFirmer the value for firm.name_firmer
     *
     * @mbggenerated
     */
    public void setNameFirmer(String nameFirmer) {
        this.nameFirmer = nameFirmer == null ? null : nameFirmer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.mail
     *
     * @return the value of firm.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.mail
     *
     * @param mail the value for firm.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.phone
     *
     * @return the value of firm.phone
     *
     * @mbggenerated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.phone
     *
     * @param phone the value for firm.phone
     *
     * @mbggenerated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.zhanghao
     *
     * @return the value of firm.zhanghao
     *
     * @mbggenerated
     */
    public String getZhanghao() {
        return zhanghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.zhanghao
     *
     * @param zhanghao the value for firm.zhanghao
     *
     * @mbggenerated
     */
    public void setZhanghao(String zhanghao) {
        this.zhanghao = zhanghao == null ? null : zhanghao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm.category
     *
     * @return the value of firm.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm.category
     *
     * @param category the value for firm.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}