package me.opims.model;

import java.util.Date;

public class job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id_job
     *
     * @mbggenerated
     */
    private Integer idJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.name_job
     *
     * @mbggenerated
     */
    private String nameJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id_firm
     *
     * @mbggenerated
     */
    private Integer idFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.category_job
     *
     * @mbggenerated
     */
    private String categoryJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.time_job
     *
     * @mbggenerated
     */
    private String timeJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.peoples
     *
     * @mbggenerated
     */
    private Integer peoples;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id_job
     *
     * @return the value of job.id_job
     *
     * @mbggenerated
     */
    public Integer getIdJob() {
        return idJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id_job
     *
     * @param idJob the value for job.id_job
     *
     * @mbggenerated
     */
    public void setIdJob(Integer idJob) {
        this.idJob = idJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.name_job
     *
     * @return the value of job.name_job
     *
     * @mbggenerated
     */
    public String getNameJob() {
        return nameJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.name_job
     *
     * @param nameJob the value for job.name_job
     *
     * @mbggenerated
     */
    public void setNameJob(String nameJob) {
        this.nameJob = nameJob == null ? null : nameJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id_firm
     *
     * @return the value of job.id_firm
     *
     * @mbggenerated
     */
    public Integer getIdFirm() {
        return idFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id_firm
     *
     * @param idFirm the value for job.id_firm
     *
     * @mbggenerated
     */
    public void setIdFirm(Integer idFirm) {
        this.idFirm = idFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.category_job
     *
     * @return the value of job.category_job
     *
     * @mbggenerated
     */
    public String getCategoryJob() {
        return categoryJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.category_job
     *
     * @param categoryJob the value for job.category_job
     *
     * @mbggenerated
     */
    public void setCategoryJob(String categoryJob) {
        this.categoryJob = categoryJob == null ? null : categoryJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.time_job
     *
     * @return the value of job.time_job
     *
     * @mbggenerated
     */
    public String getTimeJob() {
        return timeJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.time_job
     *
     * @param timeJob the value for job.time_job
     *
     * @mbggenerated
     */
    public void setTimeJob(String timeJob) {
        this.timeJob = timeJob == null ? null : timeJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.date
     *
     * @return the value of job.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.date
     *
     * @param date the value for job.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.peoples
     *
     * @return the value of job.peoples
     *
     * @mbggenerated
     */
    public Integer getPeoples() {
        return peoples;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.peoples
     *
     * @param peoples the value for job.peoples
     *
     * @mbggenerated
     */
    public void setPeoples(Integer peoples) {
        this.peoples = peoples;
    }
}