package me.opims.model;

import java.util.Date;

public class post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id_post
     *
     * @mbggenerated
     */
    private Integer idPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.bt_post
     *
     * @mbggenerated
     */
    private String btPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.xq_post
     *
     * @mbggenerated
     */
    private String xqPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.date_fb
     *
     * @mbggenerated
     */
    private Date dateFb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.date_sx
     *
     * @mbggenerated
     */
    private Date dateSx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id_post
     *
     * @return the value of post.id_post
     *
     * @mbggenerated
     */
    public Integer getIdPost() {
        return idPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id_post
     *
     * @param idPost the value for post.id_post
     *
     * @mbggenerated
     */
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.bt_post
     *
     * @return the value of post.bt_post
     *
     * @mbggenerated
     */
    public String getBtPost() {
        return btPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.bt_post
     *
     * @param btPost the value for post.bt_post
     *
     * @mbggenerated
     */
    public void setBtPost(String btPost) {
        this.btPost = btPost == null ? null : btPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.xq_post
     *
     * @return the value of post.xq_post
     *
     * @mbggenerated
     */
    public String getXqPost() {
        return xqPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.xq_post
     *
     * @param xqPost the value for post.xq_post
     *
     * @mbggenerated
     */
    public void setXqPost(String xqPost) {
        this.xqPost = xqPost == null ? null : xqPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.date_fb
     *
     * @return the value of post.date_fb
     *
     * @mbggenerated
     */
    public Date getDateFb() {
        return dateFb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.date_fb
     *
     * @param dateFb the value for post.date_fb
     *
     * @mbggenerated
     */
    public void setDateFb(Date dateFb) {
        this.dateFb = dateFb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.date_sx
     *
     * @return the value of post.date_sx
     *
     * @mbggenerated
     */
    public Date getDateSx() {
        return dateSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.date_sx
     *
     * @param dateSx the value for post.date_sx
     *
     * @mbggenerated
     */
    public void setDateSx(Date dateSx) {
        this.dateSx = dateSx;
    }
}